clk: idt: Fix incompatible function pointer types error
Fix below error reported by kernel test robot.

>> drivers/clk/idt/clk-idt8t49n24x.c:631:11: error: incompatible
>> function pointer types initializing 'int (*)(struct i2c_client *)'
>> with an expression of type 'int (struct i2c_client *, const struct
>> i2c_device_id *)' [-Wincompatible-function-pointer-types]
     631 |         .probe = idt24x_probe,
         |                  ^~~~~~~~~~~~
   1 error generated.

Fixes: dbb6c143bf78 ("Revert "Revert "clk: Add ccf driver for IDT 8T49N24x UFT""")
Signed-off-by: Rajesh Gugulothu <rajesh.gugulothu@amd.com>
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202408040958.Sxhrb7X9-lkp@intel.com/